# -*- coding: utf-8 -*-
"""CSCA5632_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XPEboicgM114BMVNDCDHrRO0d3gJ5ue
"""

#  Imports --
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.metrics import silhouette_score
import matplotlib.pyplot

# Load dataset
df = pd.read_csv("https://raw.githubusercontent.com/Solomon1533/CSCA-5632---Final-Project/main/Asthma.csv")



# Initialize PCA
pca = PCA()

# Scale the data first
scaler = StandardScaler()
df_numeric = df.select_dtypes(include=np.number) # Select only numeric columns
df_scaled = scaler.fit_transform(df_numeric)

# Fit PCA on the scaled data and transform it
df_pca = pca.fit_transform(df_scaled)

# Create a DataFrame for the PCA results
df_pca = pd.DataFrame(df_pca, columns=[f'PC_{i+1}' for i in range(df_pca.shape[1])])

# Display the explained variance ratio
print("Explained variance ratio of each principal component:")
print(pca.explained_variance_ratio_)

# Display cumulative explained variance
cum_explained_variance = np.cumsum(pca.explained_variance_ratio_)
print("\nCumulative explained variance:")
print(cum_explained_variance)

# Display the first 5 rows of the PCA-transformed data
display(df_pca.head())

#Select features for clustering --
cluster_features = [
 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
 'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
 'PollutionExposure', 'PollenExposure', 'DustExposure',
 'PetAllergy', 'FamilyHistoryAsthma', 'HistoryOfAllergies',
 'Eczema', 'HayFever', 'GastroesophagealReflux',
 'LungFunctionFEV1', 'LungFunctionFVC',
 'Wheezing', 'ShortnessOfBreath', 'ChestTightness',
 'Coughing', 'NighttimeSymptoms', 'ExerciseInduced'
 ]
X = df[cluster_features].copy()

# Identify categorical columns (excluding binary ones that are already encoded as 0/1)
categorical_cols = [
    'Gender', 'Ethnicity', 'EducationLevel', 'Smoking', 'PetAllergy',
    'FamilyHistoryAsthma', 'HistoryOfAllergies', 'Eczema', 'HayFever',
    'GastroesophagealReflux', 'Wheezing', 'ShortnessOfBreath',
    'ChestTightness', 'Coughing', 'NighttimeSymptoms', 'ExerciseInduced',
    'Diagnosis'
]



# 'Ethnicity' and 'EducationLevel' seem to be ordinal/multi-class based on df.describe() max values (3 and 3 respectively)
# Given the nature of clustering, we will treat 'Ethnicity' and 'EducationLevel' as ordinal
print("Value counts for 'Ethnicity':")
print(df['Ethnicity'].value_counts())
print("\nValue counts for 'EducationLevel':")
print(df['EducationLevel'].value_counts())

display(df.head())

#K-Means --
# Scale the features before applying K-Means
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_labels = kmeans.fit_predict(X_scaled)
sil_km = silhouette_score(X_scaled, kmeans_labels)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import numpy as np
import matplotlib.pyplot as plt

#Elbow & Silhouette Analysis --

# Scale the features before applying K-Means
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

inertias = []
silhouette_scores = []
k_values = range(2, 11)  # testing cluster counts from 2 to 10
for k in k_values:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(X_scaled)
    inertias.append(kmeans.inertia_)
    sil_score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(sil_score)

# --- Plot results --
fig, ax1 = plt.subplots(figsize=(10, 5))

# Elbow method (inertia)
ax1.plot(k_values, inertias, 'bo-', label='Inertia (Elbow Method)')
ax1.set_xlabel('Number of clusters (k)')
ax1.set_ylabel('Inertia', color='b')
ax1.tick_params(axis='y', labelcolor='b')
ax1.set_title("Elbow & Silhouette Method for Optimal k")

# Silhouette score (on second axis)
ax2 = ax1.twinx()
ax2.plot(k_values, silhouette_scores, 'ro-', label='Silhouette Score')
ax2.set_ylabel('Silhouette Score', color='r')
ax2.tick_params(axis='y', labelcolor='r')

# Combine legends
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines + lines2, labels + labels2, loc='best')
plt.show()

# --- Print recommended k --
best_k = k_values[np.argmax(silhouette_scores)]
print(f"\n\n ✅\n Recommended cluster count based on highest silhouette score: {best_k}")

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import seaborn as sns

pca = PCA(n_components=2)
reduced_data = pca.fit_transform(X_scaled)
plt.figure(figsize=(10, 6))
plt.scatter(
 reduced_data[:, 0],
 reduced_data[:, 1],
 c=kmeans_labels,
 cmap='viridis',
 alpha=0.6
 )
plt.title(f"K-Means Clustering Visualization (k={best_k})")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.colorbar(label="Cluster")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

 #Hierarchical (Agglomerative) --
agg = AgglomerativeClustering(n_clusters=4)
agg_labels = agg.fit_predict(X_scaled)
sil_agg = silhouette_score(X_scaled, agg_labels)
cluster_features = [
    'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
    'Smoking', 'PhysicalActivity', 'DietQuality', 'SleepQuality',
    'PollutionExposure', 'PollenExposure', 'DustExposure',
    'PetAllergy', 'FamilyHistoryAsthma', 'HistoryOfAllergies',
    'Eczema', 'HayFever', 'GastroesophagealReflux',
    'LungFunctionFEV1', 'LungFunctionFVC',
    'Wheezing', 'ShortnessOfBreath', 'ChestTightness',
    'Coughing', 'NighttimeSymptoms', 'ExerciseInduced'
]
X = df[cluster_features].copy()
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
reduced_data = pca.fit_transform(X_scaled)

# Hierarchical cluster labels (agg_labels) are available from above cell
# sil_agg is also available from that cell

plt.figure(figsize=(10, 6))
scatter = plt.scatter(
    x=reduced_data[:, 0],
    y=reduced_data[:, 1],
    c=agg_labels, # Use hierarchical cluster labels
    cmap='tab10',
    alpha=0.6
)
plt.title(f'Hierarchical Clusters (Silhouette={sil_agg:.2f})')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.colorbar(scatter, label='Cluster') # Pass the scatter object to colorbar
plt.show()

#Dendrogram Visualization --
from scipy.cluster.hierarchy import linkage, dendrogram

Z = linkage(X_scaled, method='ward')

# Plot dendrogram --
plt.figure(figsize=(14, 6))
plt.title("Hierarchical Clustering Dendrogram (Ward Linkage)")
plt.xlabel("Sample Index (Patients)")
plt.ylabel("Distance (Cluster Merge Height)")
# truncate_mode='level' shows only the top levels for readability
dendrogram( Z,  truncate_mode='level',p=6,
# show top 6 levels of the hierarchy
color_threshold=0.7 * max(Z[:, 2]),  # threshold for color separation
leaf_rotation=90.,
leaf_font_size=8.,
show_contracted=True
)
plt.show()

import pandas as pd

# Assuming X, X_scaled, and kmeans_labels are available from previous steps

# Create a DataFrame from X_scaled with feature names and add cluster labels
df_scaled_clusters = pd.DataFrame(X_scaled, columns=X.columns)
df_scaled_clusters['cluster'] = kmeans_labels

# Calculate the mean of each feature for each cluster
cluster_profile = df_scaled_clusters.groupby('cluster').mean()

# Scale the cluster profiles
scaler_cluster_profile = StandardScaler()
cluster_profile_scaled = pd.DataFrame(
    scaler_cluster_profile.fit_transform(cluster_profile),
    columns=cluster_profile.columns,
    index=cluster_profile.index
)

# Plot radar chart for each cluster
features = cluster_profile_scaled.columns.tolist()
num_vars = len(features)
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]  # close the loop
plt.figure(figsize=(10, 8))
for cluster_id, row in cluster_profile_scaled.iterrows():
    values = row.tolist()
    values += values[:1]  # close loop
    plt.polar(angles, values, label=f"Cluster {cluster_id}", linewidth=2)
plt.xticks(angles[:-1], features, color='black', size=8)
plt.title("Asthma Patient Cluster Profiles (Radar Chart)", size=14, y=1.1)
plt.legend(loc='upper right', bbox_to_anchor=(1.2, 1.1))
plt.tight_layout()
plt.show()